### ISSUE TITLE
Change the values in en.yml that refer to Authy

### ISSUE THREAD

**Issue by wwahammy** [MidwestAccessCoalition/twilio-verify-devise#82]
If one of the values in en.yml refer to Authy, they need to be changed appropriately.

I don't remember how these were overridden in https://github.com/MidwestAccessCoalition/cashbox but it might be worth seeing if they were overridden and whether they make sense.

**Comment by camckin10** [comment]
@wwahammy There are no references `authy' in the 'en.yml' file or the 'devise.en.yml' file. 
I did find a 'devise.authy.en.yml' file. Did you mean for that file to be deleted or changed?

**Comment by camckin10** [comment]
@wwahammy Is this the appropriate manner? This info was taken from the Twilio-authy-devise readme: 

`Do a project code wide search & replace of these terms
devise-authy -> devise-twilio-verify
authy_ -> twilio_verify_
_authy -> _twilio_verify
authy- -> twilio-verify-
-authy -> -twilio-verify
Authy -> TwilioVerify`

**Comment by wwahammy** [comment]
> @wwahammy Is this the appropriate manner? This info was taken from the Twilio-authy-devise readme:
> 
> Do a project code wide search & replace of these terms
> 
>     * devise-authy -> devise-twilio-verify
> 
>     * authy_ -> twilio_verify_
> 
>     * _authy -> _twilio_verify
> 
>     * authy- -> twilio-verify-
> 
>     * -authy -> -twilio-verify
> 
>     * Authy -> TwilioVerify

We're only looking to change the authy in the values in en.yml, not the keys. I've edited the issue to better reflect that.

More generally, while jayywolff's fork may be a good reference, we made different design decisions than he did. So his changes and decisions may or may not be appropriate.
