### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by wwahammy** [MidwestAccessCoalition/twilio-verify-devise#83]
We've made a ton of changes so let's get the README up to date.

**Comment by camckin10** [comment]
@wwahammy  What information do I need to include in the ReadMe to get the content up to date?

**Comment by camckin10** [comment]
Initial readme contents found [here:](https://github.com/jayywolff/twilio-verify-devise/blob/master/README.md)

Break up readme into chunks:

1. Migration Steps
2. Twilio Verify Readme contents (title of sections)
3. Pre-requisites 
4. Custom views
5. Custom redirect Rails
6. I18n
7. Session Variables 
8. Generic authenticator token support 
9. Rails 5 CSRF(Cross-site request forgery) Protection
10. Running Tests 
11. Copyright

**Comment by wwahammy** [comment]
> Initial readme contents found [here:](https://github.com/jayywolff/twilio-verify-devise/blob/master/README.md)

I'm sorry, that's not the original README contents. 

The original README contents is the one we have. Jayywolff went about forking the original project in a different way than we did. Some of what he wrote might be useful but much of it won't.

**Comment by wwahammy** [comment]
We've done most of this but I'm sure there are things to do.
