### ISSUE TITLE
Move verify_mfaable into authy_authenticatable

### ISSUE THREAD

**Issue by wwahammy** [MidwestAccessCoalition/twilio-verify-devise#85]
One of the main ways to designate an model as using Devise Authy is to add [`:authy_authenticatable`](https://github.com/MidwestAccessCoalition/twilio-verify-devise/blob/main/lib/devise-authy/models/authy_authenticatable.rb) to the list of arguments in the call to the `devise` class method. Since our new replacement for authy_authenticatable doesn't really work without an mfa_config reference, it would make sense to also include the mfa_config reference there. Unfortunately, we put that into a separate module: [`:verify_mfaable`](https://github.com/MidwestAccessCoalition/twilio-verify-devise/blob/main/lib/devise-authy/models/verify_mfaable.rb). I don't foresee any situation where you wouldn't need both of them. To that end, we should move verify_mfaable into authy_authenticatable so you don't need to ever reference it.

**Comment by BintLopez** [comment]
Since we're consolidating the two and since Authy is the thing being phased out would it make more sense to consolidate under the updated naming?

**Comment by wwahammy** [comment]
I think we should change the name of this once we change the name of all of the other external APIs so they're consistent.
